name: Deploy to Production

on:
  push:
    branches: [dev]

jobs:
  get-dev-branch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_SSH_HOST }}
          username: ${{ secrets.DEPLOYMENT_SSH_USERNAME }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          script: |
            cd /repo/web02-fancamp
            git stash 
            git switch dev
            git pull origin dev
            cd frontend
            npm install
            npm run build
            sudo systemctl restart nginx 
            cd ../backend
            npm install
            npm run build
            pm2 start ./pm2/ecosystem.config.js
